export const GET_REALTIME_USERS_SUCCESS = 'GET_REALTIME_USERS_SUCCESS';
export const GET_REALTIME_USERS_FAILURE = 'GET_REALTIME_USERS_FAILURE';

export const GET_REALTIME_MESSAGES = 'GET_REALTIME_MESSAGES';
export const GET_REALTIME_MESSAGES_SUCCESS = 'GET_REALTIME_MESSAGES_SUCCESS';
export const GET_REALTIME_MESSAGES_FAILURE = 'GET_REALTIME_MESSAGES_FAILURE';
