export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCCESS = 'USER_REGISTER_SUCCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCCESS = 'USER_LOGIN_SUCCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';

export const AUTH_DELETE_ERR = 'AUTH_DELETE_ERR';
export const USER_DATA_NOT_FOUND = 'USER_DATA_NOT_FOUND';


